services:
  backend:
    image: devhaxcodes/pinger-backend:latest
    container_name: resource-pinger-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    image: devhaxcodes/pinger-frontend:latest
    container_name: resource-pinger-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
